# Generated by Django 2.1 on 2020-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_showtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieestimatedincome',
            name='income_estimated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
