# Generated by Django 2.1 on 2020-03-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_showtime', '0004_auto_20200227_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchestimesetting',
            name='first_showtime',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='branchestimesetting',
            name='last_showtime',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterIndexTogether(
            name='branchesbesttimedetail',
            index_together={('branch_nickname', 'is_active', 'created_at'), ('branch_nickname', 'is_active'), ('branch_nickname', 'created_at')},
        ),
    ]
