# Generated by Django 2.1 on 2020-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_showtime', '0005_auto_20200302_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchesScreenDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_nickname', models.CharField(max_length=5)),
                ('screen_number', models.PositiveSmallIntegerField()),
                ('screen_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'branches_screen_detail',
            },
        ),
        migrations.AlterIndexTogether(
            name='branchesscreendetail',
            index_together={('branch_nickname', 'screen_number'), ('branch_nickname', 'screen_name'), ('branch_nickname', 'screen_number', 'screen_name')},
        ),
    ]
