# Generated by Django 2.1 on 2020-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_showtime', '0006_auto_20200311_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchesscreendetail',
            name='n_seat',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
