# Generated by Django 2.1 on 2020-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major_showtime', '0007_branchesscreendetail_n_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchesRegionSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_nickname', models.CharField(max_length=5)),
                ('branch_code_vista', models.CharField(default=None, max_length=5, null=True)),
                ('branch_region', models.CharField(default=None, max_length=20, null=True)),
            ],
            options={
                'db_table': 'branches_region_setting',
            },
        ),
    ]
